const Portfolios = [
  {
    cover: 'bluefinenterprises.jpeg',
    image: 'bluefinenterprises.jpeg',
    title: 'BluefinEnterprises.com',
    description: 'Nextjs, TailwindCSS',
    url: 'https://www.bluefinenterprises.com/',
  },
  {
    cover: 'w3catalog-home.jpeg',
    image: 'w3catalog-home.jpeg',
    video: 'https://www.youtube.com/embed/QxnZa0McH5o?si=69m92GEMn3jaWfnx',
    title: 'W3catalog.com',
    description: 'Nextjs, TailwindCSS, PayloadCMS',
    url: '',
  },
  {
    cover: 'officecubicles.jpeg',
    image: 'officecubicles.jpeg',
    title: 'OfficeCubicles.com',
    description: 'Nextjs, TailwindCSS, PayloadCMS',
    url: 'https://www.officecubicles.com/',
  },
  {
    cover: 'spraypaintbooths.jpeg',
    image: 'spraypaintbooths.jpeg',
    title: 'SprayPaintBooths.com',
    description: 'Nextjs, TailwindCSS, PayloadCMS',
    url: 'https://www.spraypaintbooths.com/',
  },
  {
    cover: 'saigonpho.png',
    image: 'saigonpho.png',
    video: 'https://www.youtube.com/embed/ry933ehkmsU',
    title: 'Saigon Pho and More',
    description: 'React, SASS',
    url: 'https://www.saigonphoandmore.ca/',
  },
  {
    cover: 'devPortfolio.png',
    image: 'devPortfolio.png',
    video: 'https://www.youtube.com/embed/ruJlhNv-Dg8',
    title: 'Developer Portfolio',
    description: 'Handlebars, Express, SASS',
    url: 'https://another-portfolio.onrender.com/',
  },
  {
    cover: 'vue-quiz.png',
    image: 'vue-quiz.png',
    title: 'Vue Quiz',
    description: 'Vue, CSS',
    url: 'https://vue-quiz-t2a8.onrender.com/',
  },
  {
    cover: 'wnfashion-express.png',
    image: 'wnfashion-express.png',
    title: 'WayneStore',
    description: 'MongoDB, Express, React, SASS',
    url: 'https://wnfashion-express.onrender.com/',
  },
  {
    cover: 'wnfashion.png',
    image: 'wnfashion.png',
    title: 'WayneStore',
    description: 'React, Redux, Strapi, SASS',
    url: '',
  },
  {
    cover: 'banhmioi.png',
    image: 'banhmioi.png',
    title: 'Banh Mi Oi',
    description: 'HTML, CSS, Javascript',
    url: 'https://banhmioi-git-master-waynenguyen1302.vercel.app/',
  },
  {
    cover: 'booknow-cover.png',
    image: 'booknow.png',
    title: 'Booknow.com - My First MERN App',
    description: 'MongoDB, Express, React, Node',
    url: 'https://booknow-com-frontend.onrender.com/',
  },
  {
    cover: 'admin-cover.png',
    image: 'admin-dashboard.png',
    title: 'Admin Dashboard',
    description: 'React, SASS',
    url: 'https://admin-dashboard-nine-eta.vercel.app/users',
  },
  {
    cover: 'mystore.png',
    image: 'mystore.png',
    title: 'Ecommerce Website',
    description: 'NEXTjs, Sanity, Stripe',
    url: 'https://my-store-ecommerce-wn.vercel.app/',
  },
  {
    cover: 'toctoc-clone.png',
    image: 'toctoc-clone.png',
    title: 'TocToc Clone',
    description: 'TypeScript, NEXTjs, Sanity, Tailwind',
    url: 'https://toctoc-clone-wsmz.vercel.app/',
  },
  {
    cover: 'task-tracker.png',
    image: 'task-tracker.png',
    title: 'Personal Task Tracker',
    description: 'Express, Handlebars',
    url: 'https://tasktracker-app-n1rh.onrender.com/',
  },
  {
    cover: 'smoothie-on-earth.png',
    image: 'smoothie-on-earth.png',
    title: 'Smoothie On Earth',
    description: 'HTML, CSS, JavaScript',
    url: '',
  },
  {
    cover: 'dmc.png',
    image: 'dmc.png',
    title: 'DMC - College Project',
    description: 'HTML, CSS, JavaScript',
    url: '',
  },
  {
    cover: 'chayTO-cover.png',
    image: 'chayTO.png',
    title: 'Chay Toronto',
    description: 'Wordpress, HTML, CSS',
    url: '',
  },
  {
    cover: 'nirvana-cover.png',
    image: 'nirvana.png',
    title: 'Nirvana Spa',
    description: 'Wordpress, HTML, CSS',
    url: '',
  },
]

export default Portfolios
